/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as MenuForgotPasswordRouteImport } from './routes/menu/forgot-password'
import { Route as MenuLoginRouteImport } from './routes/menu/login'
import { Route as MenuAgendaIndexRouteImport } from './routes/menu/agenda/index'
import { Route as MenuClientesIndexRouteImport } from './routes/menu/clientes/index'
import { Route as MenuComandasIndexRouteImport } from './routes/menu/comandas/index'
import { Route as MenuComandasIdRouteImport } from './routes/menu/comandas/$id'
import { Route as MenuConfigIndexRouteImport } from './routes/menu/config/index'
import { Route as MenuFinanceiroIndexRouteImport } from './routes/menu/financeiro/index'
import { Route as MenuLembretesIndexRouteImport } from './routes/menu/lembretes/index'
import { Route as MenuMetricasIndexRouteImport } from './routes/menu/metricas/index'
import { Route as MenuProcedimentosIndexRouteImport } from './routes/menu/procedimentos/index'
import { Route as MenuProdutosIndexRouteImport } from './routes/menu/produtos/index'
import { Route as MenuClientesIdFichasIndexRouteImport } from './routes/menu/clientes/$id/fichas/index'
import { Route as MenuClientesIdFichasFichaIdRouteImport } from './routes/menu/clientes/$id/fichas/$fichaId'
import { Route as MenuClientesIdFichasNovaRouteImport } from './routes/menu/clientes/$id/fichas/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuForgotPasswordRoute = MenuForgotPasswordRouteImport.update({
  id: '/menu/forgot-password',
  path: '/menu/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuLoginRoute = MenuLoginRouteImport.update({
  id: '/menu/login',
  path: '/menu/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuAgendaIndexRoute = MenuAgendaIndexRouteImport.update({
  id: '/menu/agenda/',
  path: '/menu/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuClientesIndexRoute = MenuClientesIndexRouteImport.update({
  id: '/menu/clientes/',
  path: '/menu/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuComandasIndexRoute = MenuComandasIndexRouteImport.update({
  id: '/menu/comandas/',
  path: '/menu/comandas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuComandasIdRoute = MenuComandasIdRouteImport.update({
  id: '/menu/comandas/$id',
  path: '/menu/comandas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuConfigIndexRoute = MenuConfigIndexRouteImport.update({
  id: '/menu/config/',
  path: '/menu/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuFinanceiroIndexRoute = MenuFinanceiroIndexRouteImport.update({
  id: '/menu/financeiro/',
  path: '/menu/financeiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuLembretesIndexRoute = MenuLembretesIndexRouteImport.update({
  id: '/menu/lembretes/',
  path: '/menu/lembretes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuMetricasIndexRoute = MenuMetricasIndexRouteImport.update({
  id: '/menu/metricas/',
  path: '/menu/metricas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuProcedimentosIndexRoute = MenuProcedimentosIndexRouteImport.update({
  id: '/menu/procedimentos/',
  path: '/menu/procedimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuProdutosIndexRoute = MenuProdutosIndexRouteImport.update({
  id: '/menu/produtos/',
  path: '/menu/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuClientesIdFichasIndexRoute =
  MenuClientesIdFichasIndexRouteImport.update({
    id: '/menu/clientes/$id/fichas/',
    path: '/menu/clientes/$id/fichas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuClientesIdFichasFichaIdRoute =
  MenuClientesIdFichasFichaIdRouteImport.update({
    id: '/menu/clientes/$id/fichas/$fichaId',
    path: '/menu/clientes/$id/fichas/$fichaId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuClientesIdFichasNovaRoute =
  MenuClientesIdFichasNovaRouteImport.update({
    id: '/menu/clientes/$id/fichas/nova',
    path: '/menu/clientes/$id/fichas/nova',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu/forgot-password': typeof MenuForgotPasswordRoute
  '/menu/login': typeof MenuLoginRoute
  '/menu/': typeof MenuIndexRoute
  '/menu/comandas/$id': typeof MenuComandasIdRoute
  '/menu/agenda/': typeof MenuAgendaIndexRoute
  '/menu/clientes/': typeof MenuClientesIndexRoute
  '/menu/comandas/': typeof MenuComandasIndexRoute
  '/menu/config/': typeof MenuConfigIndexRoute
  '/menu/financeiro/': typeof MenuFinanceiroIndexRoute
  '/menu/lembretes/': typeof MenuLembretesIndexRoute
  '/menu/metricas/': typeof MenuMetricasIndexRoute
  '/menu/procedimentos/': typeof MenuProcedimentosIndexRoute
  '/menu/produtos/': typeof MenuProdutosIndexRoute
  '/menu/clientes/$id/fichas/$fichaId': typeof MenuClientesIdFichasFichaIdRoute
  '/menu/clientes/$id/fichas/nova': typeof MenuClientesIdFichasNovaRoute
  '/menu/clientes/$id/fichas/': typeof MenuClientesIdFichasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu/forgot-password': typeof MenuForgotPasswordRoute
  '/menu/login': typeof MenuLoginRoute
  '/menu': typeof MenuIndexRoute
  '/menu/comandas/$id': typeof MenuComandasIdRoute
  '/menu/agenda': typeof MenuAgendaIndexRoute
  '/menu/clientes': typeof MenuClientesIndexRoute
  '/menu/comandas': typeof MenuComandasIndexRoute
  '/menu/config': typeof MenuConfigIndexRoute
  '/menu/financeiro': typeof MenuFinanceiroIndexRoute
  '/menu/lembretes': typeof MenuLembretesIndexRoute
  '/menu/metricas': typeof MenuMetricasIndexRoute
  '/menu/procedimentos': typeof MenuProcedimentosIndexRoute
  '/menu/produtos': typeof MenuProdutosIndexRoute
  '/menu/clientes/$id/fichas/$fichaId': typeof MenuClientesIdFichasFichaIdRoute
  '/menu/clientes/$id/fichas/nova': typeof MenuClientesIdFichasNovaRoute
  '/menu/clientes/$id/fichas': typeof MenuClientesIdFichasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu/forgot-password': typeof MenuForgotPasswordRoute
  '/menu/login': typeof MenuLoginRoute
  '/menu/': typeof MenuIndexRoute
  '/menu/comandas/$id': typeof MenuComandasIdRoute
  '/menu/agenda/': typeof MenuAgendaIndexRoute
  '/menu/clientes/': typeof MenuClientesIndexRoute
  '/menu/comandas/': typeof MenuComandasIndexRoute
  '/menu/config/': typeof MenuConfigIndexRoute
  '/menu/financeiro/': typeof MenuFinanceiroIndexRoute
  '/menu/lembretes/': typeof MenuLembretesIndexRoute
  '/menu/metricas/': typeof MenuMetricasIndexRoute
  '/menu/procedimentos/': typeof MenuProcedimentosIndexRoute
  '/menu/produtos/': typeof MenuProdutosIndexRoute
  '/menu/clientes/$id/fichas/$fichaId': typeof MenuClientesIdFichasFichaIdRoute
  '/menu/clientes/$id/fichas/nova': typeof MenuClientesIdFichasNovaRoute
  '/menu/clientes/$id/fichas/': typeof MenuClientesIdFichasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu/forgot-password'
    | '/menu/login'
    | '/menu/'
    | '/menu/comandas/$id'
    | '/menu/agenda/'
    | '/menu/clientes/'
    | '/menu/comandas/'
    | '/menu/config/'
    | '/menu/financeiro/'
    | '/menu/lembretes/'
    | '/menu/metricas/'
    | '/menu/procedimentos/'
    | '/menu/produtos/'
    | '/menu/clientes/$id/fichas/$fichaId'
    | '/menu/clientes/$id/fichas/nova'
    | '/menu/clientes/$id/fichas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu/forgot-password'
    | '/menu/login'
    | '/menu'
    | '/menu/comandas/$id'
    | '/menu/agenda'
    | '/menu/clientes'
    | '/menu/comandas'
    | '/menu/config'
    | '/menu/financeiro'
    | '/menu/lembretes'
    | '/menu/metricas'
    | '/menu/procedimentos'
    | '/menu/produtos'
    | '/menu/clientes/$id/fichas/$fichaId'
    | '/menu/clientes/$id/fichas/nova'
    | '/menu/clientes/$id/fichas'
  id:
    | '__root__'
    | '/'
    | '/menu/forgot-password'
    | '/menu/login'
    | '/menu/'
    | '/menu/comandas/$id'
    | '/menu/agenda/'
    | '/menu/clientes/'
    | '/menu/comandas/'
    | '/menu/config/'
    | '/menu/financeiro/'
    | '/menu/lembretes/'
    | '/menu/metricas/'
    | '/menu/procedimentos/'
    | '/menu/produtos/'
    | '/menu/clientes/$id/fichas/$fichaId'
    | '/menu/clientes/$id/fichas/nova'
    | '/menu/clientes/$id/fichas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuForgotPasswordRoute: typeof MenuForgotPasswordRoute
  MenuLoginRoute: typeof MenuLoginRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenuComandasIdRoute: typeof MenuComandasIdRoute
  MenuAgendaIndexRoute: typeof MenuAgendaIndexRoute
  MenuClientesIndexRoute: typeof MenuClientesIndexRoute
  MenuComandasIndexRoute: typeof MenuComandasIndexRoute
  MenuConfigIndexRoute: typeof MenuConfigIndexRoute
  MenuFinanceiroIndexRoute: typeof MenuFinanceiroIndexRoute
  MenuLembretesIndexRoute: typeof MenuLembretesIndexRoute
  MenuMetricasIndexRoute: typeof MenuMetricasIndexRoute
  MenuProcedimentosIndexRoute: typeof MenuProcedimentosIndexRoute
  MenuProdutosIndexRoute: typeof MenuProdutosIndexRoute
  MenuClientesIdFichasFichaIdRoute: typeof MenuClientesIdFichasFichaIdRoute
  MenuClientesIdFichasNovaRoute: typeof MenuClientesIdFichasNovaRoute
  MenuClientesIdFichasIndexRoute: typeof MenuClientesIdFichasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/forgot-password': {
      id: '/menu/forgot-password'
      path: '/menu/forgot-password'
      fullPath: '/menu/forgot-password'
      preLoaderRoute: typeof MenuForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/login': {
      id: '/menu/login'
      path: '/menu/login'
      fullPath: '/menu/login'
      preLoaderRoute: typeof MenuLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/agenda/': {
      id: '/menu/agenda/'
      path: '/menu/agenda'
      fullPath: '/menu/agenda/'
      preLoaderRoute: typeof MenuAgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/clientes/': {
      id: '/menu/clientes/'
      path: '/menu/clientes'
      fullPath: '/menu/clientes/'
      preLoaderRoute: typeof MenuClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/comandas/': {
      id: '/menu/comandas/'
      path: '/menu/comandas'
      fullPath: '/menu/comandas/'
      preLoaderRoute: typeof MenuComandasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/comandas/$id': {
      id: '/menu/comandas/$id'
      path: '/menu/comandas/$id'
      fullPath: '/menu/comandas/$id'
      preLoaderRoute: typeof MenuComandasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/config/': {
      id: '/menu/config/'
      path: '/menu/config'
      fullPath: '/menu/config/'
      preLoaderRoute: typeof MenuConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/financeiro/': {
      id: '/menu/financeiro/'
      path: '/menu/financeiro'
      fullPath: '/menu/financeiro/'
      preLoaderRoute: typeof MenuFinanceiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/lembretes/': {
      id: '/menu/lembretes/'
      path: '/menu/lembretes'
      fullPath: '/menu/lembretes/'
      preLoaderRoute: typeof MenuLembretesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/metricas/': {
      id: '/menu/metricas/'
      path: '/menu/metricas'
      fullPath: '/menu/metricas/'
      preLoaderRoute: typeof MenuMetricasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/procedimentos/': {
      id: '/menu/procedimentos/'
      path: '/menu/procedimentos'
      fullPath: '/menu/procedimentos/'
      preLoaderRoute: typeof MenuProcedimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/produtos/': {
      id: '/menu/produtos/'
      path: '/menu/produtos'
      fullPath: '/menu/produtos/'
      preLoaderRoute: typeof MenuProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/clientes/$id/fichas/': {
      id: '/menu/clientes/$id/fichas/'
      path: '/menu/clientes/$id/fichas'
      fullPath: '/menu/clientes/$id/fichas/'
      preLoaderRoute: typeof MenuClientesIdFichasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/clientes/$id/fichas/$fichaId': {
      id: '/menu/clientes/$id/fichas/$fichaId'
      path: '/menu/clientes/$id/fichas/$fichaId'
      fullPath: '/menu/clientes/$id/fichas/$fichaId'
      preLoaderRoute: typeof MenuClientesIdFichasFichaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/clientes/$id/fichas/nova': {
      id: '/menu/clientes/$id/fichas/nova'
      path: '/menu/clientes/$id/fichas/nova'
      fullPath: '/menu/clientes/$id/fichas/nova'
      preLoaderRoute: typeof MenuClientesIdFichasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuForgotPasswordRoute: MenuForgotPasswordRoute,
  MenuLoginRoute: MenuLoginRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenuComandasIdRoute: MenuComandasIdRoute,
  MenuAgendaIndexRoute: MenuAgendaIndexRoute,
  MenuClientesIndexRoute: MenuClientesIndexRoute,
  MenuComandasIndexRoute: MenuComandasIndexRoute,
  MenuConfigIndexRoute: MenuConfigIndexRoute,
  MenuFinanceiroIndexRoute: MenuFinanceiroIndexRoute,
  MenuLembretesIndexRoute: MenuLembretesIndexRoute,
  MenuMetricasIndexRoute: MenuMetricasIndexRoute,
  MenuProcedimentosIndexRoute: MenuProcedimentosIndexRoute,
  MenuProdutosIndexRoute: MenuProdutosIndexRoute,
  MenuClientesIdFichasFichaIdRoute: MenuClientesIdFichasFichaIdRoute,
  MenuClientesIdFichasNovaRoute: MenuClientesIdFichasNovaRoute,
  MenuClientesIdFichasIndexRoute: MenuClientesIdFichasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
